use_frameworks!

target 'MVVMSupport_Example' do
  pod 'MVVMSupport', :path => '../'

  target 'MVVMSupport_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
