use_frameworks!

target 'MVVMSupport_Example' do
  pod 'CleanRxMVVMSupport', :path => '../'

  target 'MVVMSupport_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
